### PR TITLE
Added I2C and Release Versioning

### PR DESCRIPTION
**Pull request by Bucknalla**
This PR adds the I2C functionality with mode toggling (to support the testbot hat) as well as dynamic firmware versioning based upon the release tag.

### CODE REVIEW

**Comment by Bucknalla** [comment]
Waiting on confirmation that this is working within the testbot configuration before this is ready for review.

**Comment by Bucknalla** [comment]
Need to add error handling for I2C because currently firmata implementation doesnt allow for errors on I2C R/W. Best way to do this is with a SYSEX msg from the host and msg handler on the client. @rcooke-warwick

**Comment by roman-mazur** [comment]
@Bucknalla since FD is down, would you attach a hex file here in a comment?

**Comment by Bucknalla** [comment]
@roman-mazur try this, had to compress it as GitHub doesn't like .hex files.
[firmata.zip](https://github.com/balena-io/balena-fin-coprocessor-firmata/files/4514993/firmata.zip)

**Comment by roman-mazur** [comment]
Thanks, flashing...

**Pull request merged**
