### PR TITLE
Updates for v0.1.0 release

### PR DESCRIPTION
**Pull request by Bucknalla**
Number of build structure changes introduced in this release:

- Now builds from submodule to allow for shared base sdk
- Added future support for BLE libs and linkers to BGM111 and BGM13 families
- Updates CMake structure for current work flow
- Updates Silabs Gecko SDK to 5.8.0

Change-type: minor
Signed-off-by: Alex Bucknall <alexbucknall@balena.io>

### CODE REVIEW

**Comment by anujdeshpande** [comment]
@Bucknalla Should we add instructions on how to build in the top level README?
Something like - 

1. Update submodule with the command -
`git submodule update --init`
2. For balenaFin version 1.0 run 
`make bgm1b`
& for balenaFin version 1.1 run
`make bgm13`

**Comment by anujdeshpande** [comment]
I also had issues with building the project locally on my development machine after running `submodule update`, `make setup`, and `make bgm13`.

**Comment by Bucknalla** [comment]
@anujdeshpande it should now build for both `BGM13` and `BGM1B` - I don't plan to include info in the README.md about the `BGM13` as this module does not exist on any released versions of the fin so no point confusing people about its existence until it is available.

**Comment by Bucknalla** [comment]
fe3e36d8c182bb63bf55dae268c9cffa74a7f611 should handle `git submodule update --init`

**Comment by Bucknalla** [comment]
I want to just do some testing of this on a v1.0 and v1.1 before I release - concerned we might have some issues

**Comment by Bucknalla** [comment]
@anujdeshpande did you get a chance to test this against a Fin?

**Comment by Bucknalla** [comment]
Due to some issues with this building incorrectly, I'm going to close this PR and forward the history with changes to the original structure. I'd like to revisit this in the future.

**Pull request closed without merging**
